server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://140.210.194.87:3306/mealtime_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: y7000p
    password: Wmy@010806

mybatis:
  type-aliases-package: com.cqu.mealtime.entity
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名
  mapper-locations: classpath:mapper/*.xml